// Code generated by sumeru-import-gen; DO NOT EDIT.

package models

import "sumeru/core/sdk"

func init() {
	sdk.MustRegister("mail",
		&CoreUserMail{},
		&MailActivity{},
		&MailActivityPlan{},
		&MailActivityPlanTemplate{},
		&MailActivityType{},
		&MailFollower{},
		&MailMessage{},
		&MailMessageSubtype{},
		&MailNotification{},
		&MailTemplate{},
	)
}
